### ISSUE TITLE
ISupportIncrementalLoading unavailable to PCLs through nuget

### ISSUE THREAD

**Issue by ScottIsAFool** [therealjohn/IncrementalListView#1]
I have my viewmodels in a PCL which is where I would like to keep the collections that would be used for incremental loading. At the moment, the nuget package is only for a pure xamarin forms project which means my PCL has no access to the interface.

**Comment by therealjohn** [comment]
Hey Scott

The package has a dependency on Xamarin.Forms because the implementation is specific to Xamarin.Forms.ListView. How would you like to use the interface and implement it in a non-Forms project?

**Comment by ScottIsAFool** [comment]
Yep, and I appreciate the implementation would require that, but as mentioned, my viewmodels project is a PCL, a non-Forms PCL. It wouldn't need access to the implementation of the ListView, it would purely need access to the interface so that it [the interface] can be implemented in there.

**Comment by therealjohn** [comment]
I think it makes more sense to try and adapt a "IncrementalListView Plugin for Xamarin" (note, not explicitly a plugin for Xamarin.Forms). 

It doesn't seem that useful to have a PCL that just gave you the interface. You can just copy/paste the interface or create your own in your project if you want that concept. The implementation is the real meat and potatoes. I'll have a think about that since it's outside the scope of what this plugin was for. Let me know your thoughts!
